# Generated by Django 3.0.7 on 2020-08-05 04:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muzakki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ktp', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Numeric character only.')])),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Numeric character only.')])),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, choices=[('CASH', 'Tunai'), ('TRANSFER', 'Transfer')], max_length=32, null=True)),
                ('goods_delivery_type', models.CharField(blank=True, choices=[('PICKUP', 'Dijemput'), ('DELIVER', 'Diantar')], max_length=32, null=True)),
                ('pick_up_address', models.TextField(blank=True, null=True)),
                ('transfer_receipt', models.FileField(blank=True, null=True, upload_to='images/transaction')),
                ('payment_confirmation', models.BooleanField(default=False)),
                ('goods_confirmation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ZakatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('item_type', models.CharField(choices=[('MONEY', 'Uang'), ('RICE', 'Beras'), ('GOLD', 'Emas'), ('CHECK', 'Cek')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ZakatTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('muzakki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Muzakki')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction')),
                ('zakat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.ZakatType')),
            ],
        ),
    ]
