# Generated by Django 3.0.7 on 2020-07-27 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mustahik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('no_ktp', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Numeric character only.')])),
                ('phone', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Numeric character only.')])),
                ('address', models.TextField()),
                ('province', models.CharField(max_length=32)),
                ('regency', models.CharField(max_length=50)),
                ('rt', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Numeric character only.')])),
                ('rw', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Numeric character only.')])),
                ('birthdate', models.DateField()),
                ('status', models.CharField(choices=[('JANDA', 'Janda'), ('MISKIN', 'Miskin'), ('YATIM', 'Yatim')], default='MISKIN', max_length=32)),
                ('family_size', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=1)),
            ],
        ),
    ]
