# Generated by Django 3.0.7 on 2020-07-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mustahik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('no_ktp', models.CharField(max_length=32, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField()),
                ('province', models.CharField(max_length=32)),
                ('regency', models.CharField(max_length=32)),
                ('rt', models.CharField(max_length=4)),
                ('rw', models.CharField(max_length=4)),
                ('birthdate', models.DateField()),
                ('status', models.CharField(choices=[('JANDA', 'Janda'), ('MISKIN', 'Miskin'), ('YATIM', 'Yatim')], default='MISKIN', max_length=32)),
                ('family_size', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
