# Generated by Django 3.0.7 on 2020-08-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mustahik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourceinstitusi',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasourceinstitusi',
            name='pic_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
