# Generated by Django 3.0.7 on 2020-07-23 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mustahik', '0002_auto_20200716_0826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mustahik',
        ),
    ]
