# Generated by Django 3.0.7 on 2020-09-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mustahik', '0002_auto_20200816_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mustahik',
            name='photo',
            field=models.ImageField(default='images/default_photo.jpg', upload_to='images/mustahik'),
        ),
    ]
